import type { FrameShape, Vec2 } from './types.ts'
import { segmentsForQuality } from './profiles.ts'

/**
 * The "opening path" is the closed outline of the sight aperture, wound
 * counter-clockwise and centred on the origin. Everything about a frame's
 * plan view is derived from it: the moulding is generated by offsetting this
 * path outward and sweeping the cross-section around it.
 */
export interface OpeningPath {
  points: Vec2[]
  /**
   * True where the path turns a hard corner (a mitre). False along sampled
   * curves, which should be shaded smooth and may be split anywhere.
   */
  sharp: boolean[]
}

export const FRAME_SHAPES: { id: FrameShape; label: string; locksAspect?: boolean }[] = [
  { id: 'rectangle', label: 'Rectangle' },
  { id: 'square', label: 'Square', locksAspect: true },
  { id: 'circle', label: 'Circle', locksAspect: true },
  { id: 'oval', label: 'Oval' },
  { id: 'arch', label: 'Arch' },
  { id: 'hexagon', label: 'Hexagon' },
  { id: 'octagon', label: 'Octagon' },
]

export function buildOpeningPath(
  shape: FrameShape,
  width: number,
  height: number,
  quality: number,
): OpeningPath {
  const hw = width / 2
  const hh = height / 2
  const seg = segmentsForQuality(quality)

  switch (shape) {
    case 'rectangle':
    case 'square':
      return sharpPath([
        [-hw, -hh],
        [hw, -hh],
        [hw, hh],
        [-hw, hh],
      ])

    case 'circle':
    case 'oval': {
      const n = Math.max(24, seg * 4)
      const points: Vec2[] = []
      for (let i = 0; i < n; i++) {
        const a = (i / n) * Math.PI * 2
        points.push([hw * Math.cos(a), hh * Math.sin(a)])
      }
      return smoothPath(points)
    }

    case 'arch': {
      // A semicircular head springing from the tallest point that still leaves
      // straight sides. Very tall openings keep a long straight run; wide ones
      // become close to a half-round.
      const radius = hw
      const springY = hh - radius
      const n = Math.max(16, seg * 2)
      const points: Vec2[] = [
        [-hw, -hh],
        [hw, -hh],
      ]
      const sharp = [true, true]
      if (springY > -hh + 0.5) {
        points.push([hw, springY])
        sharp.push(false)
      }
      for (let i = 1; i < n; i++) {
        const a = (i / n) * Math.PI
        points.push([radius * Math.cos(a), springY + radius * Math.sin(a)])
        sharp.push(false)
      }
      points.push([-hw, springY > -hh + 0.5 ? springY : -hh])
      sharp.push(false)
      return { points, sharp }
    }

    case 'hexagon':
      return regularPolygon(6, hw, hh, Math.PI / 6)
    case 'octagon':
      return regularPolygon(8, hw, hh, Math.PI / 8)
  }
}

/**
 * A regular n-gon stretched so that it exactly fills the requested aperture
 * box, which keeps the width/height inputs meaningful for every shape.
 */
function regularPolygon(n: number, hw: number, hh: number, rotate: number): OpeningPath {
  const raw: Vec2[] = []
  for (let i = 0; i < n; i++) {
    const a = rotate + (i / n) * Math.PI * 2
    raw.push([Math.cos(a), Math.sin(a)])
  }
  const maxX = Math.max(...raw.map((p) => Math.abs(p[0])))
  const maxY = Math.max(...raw.map((p) => Math.abs(p[1])))
  return sharpPath(raw.map(([x, y]) => [(x / maxX) * hw, (y / maxY) * hh] as Vec2))
}

const sharpPath = (points: Vec2[]): OpeningPath => ({
  points,
  sharp: points.map(() => true),
})

const smoothPath = (points: Vec2[]): OpeningPath => ({
  points,
  sharp: points.map(() => false),
})

/** Outward unit normal of the edge leaving vertex i, for a CCW path. */
function edgeNormal(points: Vec2[], i: number): Vec2 {
  const a = points[i]
  const b = points[(i + 1) % points.length]
  const dx = b[0] - a[0]
  const dy = b[1] - a[1]
  const len = Math.hypot(dx, dy) || 1
  return [dy / len, -dx / len]
}

export interface MiterFrame {
  /** Outward unit bisector at this vertex. */
  dir: Vec2
  /**
   * How far along `dir` to travel per millimetre of profile width so the offset
   * edges stay parallel to the originals — i.e. a proper mitre.
   */
  scale: number
}

/**
 * Per-vertex mitre frames for offsetting a closed CCW path outward.
 *
 * Offsetting every vertex by `dir * scale * u` reproduces exact 45° mitres on a
 * rectangle, correct shallower mitres on any convex polygon, and a true
 * parallel offset along sampled curves — one formulation covers every shape.
 */
export function miterFrames(points: Vec2[]): MiterFrame[] {
  const n = points.length
  const normals = points.map((_, i) => edgeNormal(points, i))
  return points.map((_, i) => {
    const prev = normals[(i - 1 + n) % n]
    const next = normals[i]
    let mx = prev[0] + next[0]
    let my = prev[1] + next[1]
    const len = Math.hypot(mx, my)
    if (len < 1e-9) {
      // A 180° spike; fall back to the outgoing normal rather than exploding.
      return { dir: next, scale: 1 }
    }
    mx /= len
    my /= len
    const cos = mx * next[0] + my * next[1]
    // Clamp so a near-degenerate corner cannot fling a vertex to infinity.
    const scale = Math.min(6, 1 / Math.max(cos, 1e-3))
    return { dir: [mx, my], scale }
  })
}

/** Signed area — positive when the path is counter-clockwise. */
export function signedArea(points: Vec2[]): number {
  let sum = 0
  for (let i = 0; i < points.length; i++) {
    const a = points[i]
    const b = points[(i + 1) % points.length]
    sum += a[0] * b[1] - b[0] * a[1]
  }
  return sum / 2
}

/** Cumulative arc length at each vertex, plus the total perimeter. */
export function pathLengths(points: Vec2[]): { at: number[]; total: number } {
  const at: number[] = [0]
  let total = 0
  for (let i = 0; i < points.length; i++) {
    const a = points[i]
    const b = points[(i + 1) % points.length]
    total += Math.hypot(b[0] - a[0], b[1] - a[1])
    at.push(total)
  }
  return { at, total }
}

/** The opening path pushed outward by `u` millimetres along its mitre frames. */
export function offsetPath(points: Vec2[], frames: MiterFrame[], u: number): Vec2[] {
  return points.map((p, i) => {
    const { dir, scale } = frames[i]
    return [p[0] + dir[0] * scale * u, p[1] + dir[1] * scale * u] as Vec2
  })
}

/**
 * Insert extra vertices so no path edge is longer than `maxSpacing`.
 *
 * A rectangle is only four points, which leaves the splitter nowhere to cut a
 * long rail. Densifying first gives it somewhere to put a seam, while the
 * `sharp` flags stay true only at the frame's real mitres so corners are still
 * preferred over mid-rail seams.
 */
export function densifyPath(path: OpeningPath, maxSpacing: number, maxPoints = 900): OpeningPath {
  const n = path.points.length
  if (n < 2 || maxSpacing <= 0) return path

  const perimeter = pathLengths(path.points).total
  // Never exceed the vertex budget, however long the frame is.
  const spacing = Math.max(maxSpacing, perimeter / maxPoints)

  const points: Vec2[] = []
  const sharp: boolean[] = []
  for (let i = 0; i < n; i++) {
    const a = path.points[i]
    const b = path.points[(i + 1) % n]
    points.push(a)
    sharp.push(path.sharp[i])
    const length = Math.hypot(b[0] - a[0], b[1] - a[1])
    const steps = Math.ceil(length / spacing)
    for (let k = 1; k < steps; k++) {
      const t = k / steps
      points.push([a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t])
      sharp.push(false)
    }
  }
  return { points, sharp }
}
